# .streamlit/secrets.toml

SUPABASE_URL = "https://yrlqlzvhtyyzlcasviij.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybHFsenZodHl5emxjYXN2aWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTIwNDcsImV4cCI6MjA3NzEyODA0N30.a2zQkdOQYVt-EFnCt-jd20ygwn2048lb-Mtgpe-t4uw"
OPENROUTER_KEY = "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"
